server:
  port: 9234
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: order_route
          uri: lb://order
          predicates:
            - Path=/order/**

#eureka配置
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/