spring:
  application:
    name: api-gateway

#eureka配置
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/