server:
  port: 9000

spring:
  application:
    name: admin-server
#  security:
#    user:
#      name: admin
#      password: 123123
#    basic:
#      enabled: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
#    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
