server:
  port: 9232
spring:
  application:
    name: config-server
  cloud:
    # spring cloud config 配置，自动刷新url：http://localhost:9232/actutor/bus-refresh
    config:
      server:
        git:
          # 配置文件仓库地址
          uri: https://github.com/HuangXiaoyu3331/config-repo.git
          username: HuangXiaoyu3331
          password: 3331woyizhizai
          # 从远程仓库拉取下来的配置文件，会存放到本地的git仓库，basedir指的就是本地仓库的路径，不要配置在项目路径下，不然项目都会被清空
          # 不配置的话，有一个默认路径，但是出于安全考虑，还是要配置
          basedir: C:\Users\EDZ\Desktop\do
          # 文件夹路径，如果git项目中没有二级文件夹,则将引入全部配置文件,有文件夹则需添加文件夹路径
          search-paths: order,product,actuator
#eureka配置
eureka:
  instance:
    # eureka 上的 status的名称这里配置的是：应用名:端口号
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh